version: '2'

volumes:
  data:

services:
  postgres:
    image: postgres:9.6.2
    volumes:
      - data:/data
    environment:
      - POSTGRES_USER=nativo
      - POSTGRES_PASSWORD=vzGg9WRrtTkwmV7pghFuENPp
      - PGDATA=/data/pgdata
    restart: always

  phoenix:
    build: ./phoenix
    volumes:
      - ./phoenix:/code
      - data:/data/nativo
    ports:
      - "4000:4000"
    working_dir: /code
    command: bash -c "mix ecto.migrate && mix phoenix.server"
    restart: always

  pgadmin:
    image: turgon37/phppgadmin
    ports:
      - "2345:80"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_NAME=nativo
    restart: always

  graphiql:
    build: ./graphiql
    ports:
      - "4001:8080"
    environment:
      - GRAPHQL_SERVER=http://localhost:4000/graphql
    restart: always
